### ISSUE TITLE
Incorrect path searching for dependent software

### ISSUE THREAD

**Issue by andrewjrobinson** [jpuritz/dDocent#1]
The dDocent.FB script appears to lookup the location for the samtools executable and assumes that all its dependencies are also located here (e.g. rainbow, ddocent itself etc.).  While this may work in common situations, it does not play happy with HPC environments where each software is installed in its own directory and activated via 'environment modules'.  Please consider revising the software search code; looking up an environment variable such as RAINBOW_DIR etc. might be a good solution.

**Comment by jpuritz** [comment]
Thanks for the feedback.  Yes, this is something that others have discovered.  I'm working on implementing this in the next version along with a check for all installed dependencies.
