### ISSUE TITLE
Error in install_dDocent_requirements

### ISSUE THREAD

**Issue by jerowe** [jpuritz/dDocent#14]
Starting on line 54 there is a chunk of code that looks like it should install vcflib, but instead installs freebayes instead.

echo "Checking for vcflib"
if which vcfcombine &>/dev/null; then
    echo "FreeBayes is already installed"
else
        echo "Downloading and installing FreeBayes"
    git clone --recursive git://github.com/ekg/freebayes.git
        cd freebayes

**Comment by jpuritz** [comment]
vcflib is packaged as part of freebayes if you use the --recursive option.  The next line of code changes the directory into the vcflib.  Freebayes is needed for the pipeline anyway, so I just stuck with that repository.  It's no different than going directly to the vcflib github.
