### ISSUE TITLE
bedtools version

### ISSUE THREAD

**Issue by outpaddling** [jpuritz/dDocent#15]
Is it really necessary to use bedtools 2.23.0, or should the latest version work as well?

I see the note about the latest vcftools lacking certain options, but couldn't find an explanation of why bedtools 2.23.0 should be required.

Thanks,

```
Jason
```

**Comment by jpuritz** [comment]
It is necessary.  Bedtools changed the output of the coverage tool which is used for interval setting for dDocent.  Most versions before 2.23.0 will work, but none after will.

**Comment by outpaddling** [comment]
OK, thanks much.
