### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by kgturner** [jpuritz/dDocent#21]
Hi, I am very naively and very literally trying to follow your installation instructions on https://ddocent.wordpress.com/ddocent-pipeline-user-guide/. Is this " $sh install_dDocent.FB_requirements" the same as install_dDocent_requirements in the this Github repo (cuz the names are different)? A link, a mention of copying this file to the users directory, and what format is should be in (I'm guessing .sh?) would all be useful things for the naive user. If these are not the same thing, then can you tell me where to look?

**Comment by kgturner** [comment]
Actually, I have a few comments about how to make the instructions more naive-person friendly, if you are interested

**Comment by jpuritz** [comment]
yes, I would love the comments.
