### ISSUE TITLE
Add `--without-curses` samtools ./configure in the install script

### ISSUE THREAD

**Issue by isaacovercast** [jpuritz/dDocent#25]
Install fails on any cluster compute node that doesn't have curses libraries (probably most of them). This is an easy fix by updating install_dDocent_requirements line 129 to read:
    ./configure --without-curses

I would make a PR but seems silly for such a small change

**Comment by isaacovercast** [comment]
Also the link to the cd-hit tgz is bad. The new one should be: 

https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/cdhit/cd-hit-v4.6.1-2012-08-27.tgz

**Comment by jpuritz** [comment]
This is the first I've heard about the curses library problem, so I am not going to make that change at the moment.  Most folks installing on a cluster should be able to handle that problem on their own.  Thanks for pointing out the link error.
