### ISSUE TITLE
Suggestion: add bioconda installation instructions

### ISSUE THREAD

**Issue by chollenbeck** [jpuritz/dDocent#27]
The conda package manager now supports dDocent installation. You could add this alternative installation method to the documentation somewhere:

[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat-square)](http://bioconda.github.io/recipes/ddocent/README.html)
#### Easy local install with bioconda

Install Miniconda: http://conda.pydata.org/miniconda.html

Add the bioconda channel:

```
conda config --add channels bioconda
```

Create a dDocent conda environment:

```
conda create -n ddocent_env ddocent=2.1
```

Activate the dDocent environment:

```
source activate ddocent_env
```

Run dDocent:

```
dDocent ...
```

Close the environment when you're done:

```
source deactivate
```

**Comment by jpuritz** [comment]
Now, that I updated the bioconda version, this will be perfect.  Thanks.
