### ISSUE TITLE
"rename.for.dDocent" not working

### ISSUE THREAD

**Issue by ghost** [jpuritz/dDocent#3]
Hi. 

I'm pretty new to genomics and using the command line, but I was wondering if this is an easy fix:

~/Documents/ddocent-master$ ls
bars.names    install_dDocent.FB_requirements    README.md
bars.names~   install_dDocent.GATK_requirements  rename.for.dDocent
dDocent.FB    LICENSE                            Rename_for_dDocent.sh
dDocent.GATK  mergefq.pl

~/Documents/ddocent-master$ sh rename.for.dDocent bars.names
rename.for.dDocent: 9: rename.for.dDocent: Syntax error: "(" unexpected (expecting "fi")

Can't seem to get barcode file to work - instructions followed exactly as on the blog. As far as I am aware I have the newest version of dDocent.

Also, are there sample data sets to available for dDocent?

Cheers,

~ jat101

**Comment by jpuritz** [comment]
The script requires that you have files that were demultiplexed via process_radtags from Stacks and also that files are gzip compressed.  Tutorials and data sets will be posted in the next few days.
