### ISSUE TITLE
Discrepancy between dDocent_filters.sh and SNP Filtering Tutorial

### ISSUE THREAD

**Issue by slambert-git** [jpuritz/dDocent#35]
Several of the filters (allele balance, mapping quality, quality/depth) contained in dDocent_filters.sh are not run with the same parameters as the step-by-step examples in the SNP filtering tutorial. Here's the relevant line (17) in dDocent_filters.sh:

vcffilter -s -f "AB > 0.2 & AB < 0.8 | AB < 0.01 | AB > 0.99" -s -g "QR > 0 | QA > 0 " $1 | vcffilter -s -f "QUAL / DP > 0.2" | vcffilter -s -f "MQM / MQMR > 0.25 & MQM / MQMR < 1.75" > $2

And the respective parameters from the step-by-step tutorial:

AB > 0.25 & AB < 0.75 | AB < 0.01
MQM / MQMR > 0.9 & MQM / MQMR < 1.05
QUAL / DP > 0.25

**Comment by jpuritz** [comment]
The `dDocent_filters` script represents my most up-to-date filters.  The tutorial is only supposed to teach principles and philosophy.  

I recommend everyone take the time to optimize these parameters for their own data.
