### ISSUE TITLE
Incorrect error prompt

### ISSUE THREAD

**Issue by pdimens** [jpuritz/dDocent#37]
https://github.com/jpuritz/dDocent/blob/eed5a7d3b16ee7654d21916668d4fe44318f312f/dDocent#L789

When answering `no` to the incorrect count of individuals in a directory, dDocent returns an error indicating the incorrect naming convention for the individuals:
`Please double check that all fastq files are named Ind01.F.fq.gz and Ind01.R.fq.gz`
instead of how it appears correctly in different error prompts:
`Please rename individuals to: Locality_Individual.F.fq.gz`

**Comment by jpuritz** [comment]
Thanks!
