### ISSUE TITLE
"Checking for required software" not operating as expected

### ISSUE THREAD

**Issue by mstuart1** [jpuritz/dDocent#42]
When I start dDocent, I get the following error  but dDocent allows me to keep going.  This might be causing other errors downstream.  I have recently installed dDocent 2.7 and it pinged me to update quite a few dependencies.

When I looked at line 70 of the dDocent script on github, it is the requirement that seqtk be at least 1.2, mine was only 1.0.  

$ dDocent
dDocent 2.7.1 

Contact jpuritz@uri.edu with any problems 

 
Checking for required software
/local/home/michelles/14_programs/dDocent/dDocent: line 70: [: 1.0-r82: integer expression expected

All required software is installed!

dDocent run started Sun Nov 18 09:55:01 EST 2018

**Comment by jpuritz** [comment]
Fixed.  Thanks.
