### ISSUE TITLE
cannot see how config file improperly configured

### ISSUE THREAD

**Issue by nclowell** [jpuritz/dDocent#47]
Trying to run dDocent in non-interactive mode and I get an error that my config file is improperly configured:

```
")syntax error: invalid arithmetic operator (error token is "ine 202: [[: 6

Configuration file is not properly configured.  Please see example on dDocent.com or the dDocent GitHub page.
```

I copied and pasted the config file structure from the dDocent tutorial, input my parameters instead, and can't tell what's wrong (below). Am I missing something?

Thanks!

My config file:

```
Number of Processors
6
Maximum Memory
50
Trimming
yes
Assembly?
no
Type_of_Assembly

Clustering_Similarity%

Minimum within individual coverage level to include a read for assembly (K1)

Minimum number of individuals a read must be present in to include for assembly (K2)

Mapping_Reads?
yes
Mapping_Match_Value
1
Mapping_MisMatch_Value
4
Mapping_GapOpen_Penalty
6
Calling_SNPs?
yes
Email
nclowell@uw.edu
```

**Comment by jpuritz** [comment]
Are you still having trouble with this?  Both my OS X and Linux installs were able to read your configuration file.

**Comment by nclowell** [comment]
Yes still having issues - I just tried updating dDocent and trying again, but I still get the same error.

**Comment by jpuritz** [comment]
Can you send me (as an attachment) your exact file?

**Comment by nclowell** [comment]
Or course! Here it is:

[config.txt](https://github.com/jpuritz/dDocent/files/3597624/config.txt)

Thanks for your help!

**Comment by jpuritz** [comment]
Your file has windows end line characters.  It needs to have unix end line characters.  You can use an advanced plain text editor to do this for you or the program `dos2unix` on your linux system.

**Comment by nclowell** [comment]
Ahh! Thanks.
