### ISSUE TITLE
Conda dDocent recipe has incorrect FreeBayes

### ISSUE THREAD

**Issue by pdimens** [jpuritz/dDocent#48]
A fresh `conda` install of dDocent with `conda install -c bioconda ddocent` installs this version of freebayes:
```
 freebayes          bioconda/linux-64::freebayes-0.9.21.7-0
```

such that when `dDocent` is invoked, this error appears and dDocent exits:
```bash
/home/pdimens/.conda/envs/ddocent2/bin/dDocent: line 6: export: `2.7.8': not a valid identifier
dDocent 2.7.8 

Contact jpuritz@uri.edu with any problems 

 
Checking for required software
The version of FreeBayes installed in your $PATH is not optimized for dDocent.
Please install at least version 1.0.0
```

The problem is easily fixed with `conda update freebayes` though.

**Comment by jpuritz** [comment]
Hey Pavel, `conda install` actually attempts to match your downloaded resources.  The best way to get the most up-to-date version of everything is to create a new conda environment `conda create -n ddocent -c bioconda ddocent`
