### ISSUE TITLE
install_dDocent.FB_requirements

### ISSUE THREAD

**Issue by rwtaylor** [jpuritz/dDocent#5]
When installing locally, cutadapt installation fails with this error:
error: could not create '/usr/lib64/python2.6/site-packages/cutadapt': Permission denied

running `python setup.py install --user` works, but then you have to append `~/.local/bin` to the PATH

Also, FreeBays v0.9.21-19-gc003c1e is install which leads to this error/warning.

```
-bash-4.1$ dDocent.FB
dDocent 1.2

Contact jpuritz@gmail.com with any problems


Checking for required software
The version of FreeBayes installed in your $PATH is not optimized for dDocent.
Please install a version 0.9.20
```

**Comment by jpuritz** [comment]
Thanks for finding this bug!
