### ISSUE TITLE
Error with main script - EOF management

### ISSUE THREAD

**Issue by ne1s0n** [jpuritz/dDocent#62]
I encountered errors like:

```
/home/ubuntu/software/dDocent/dDocent: line 1383: warning: here-document at line 833 delimited by end-of-file (wanted `EOF')
/home/ubuntu/software/dDocent/dDocent: line 1384: syntax error: unexpected end of file
```

There are extra spaces after EOF at lines (which I removed):

https://github.com/jpuritz/dDocent/blob/master/dDocent#L778
https://github.com/jpuritz/dDocent/blob/master/dDocent#L833

I've also removed the trailing tab before EOF at lines:

https://github.com/jpuritz/dDocent/blob/master/dDocent#L789
https://github.com/jpuritz/dDocent/blob/master/dDocent#L843

And then it works fine.

dDocent version: 2.8.9
bash version: 4.4.19(1)-release (x86_64-pc-linux-gnu)

**Comment by jpuritz** [comment]
Fixed with https://github.com/jpuritz/dDocent/commit/66b1f7a756017ddd3866f5327b98c507e4cf8b3b
