### ISSUE TITLE
Program stuck in using BWA mapping reads

### ISSUE THREAD

**Issue by Liut035** [jpuritz/dDocent#65]
Hi,

I am running dDocent for 164 individuals with pair-end sequencing and reference genome on dDocent 2.7.8. I used a configuration file to run in HPC. The trimming step went really well, while now I'm stuck in mapping reads with bwa. It had been stuck in one of my individuals for more than ten hours, and can not generate *-RG.bam and *-RG.bam.bai, and nothing in its *.bam.log file. My raw data is about 60 GB, and I set the maximum memory to 200G, while now there are a total of 151GB files, is this the reason? 

Here is the config.file I used.

_Number of Processors
20
Maximum Memory
200
Trimming
yes
Assembly?
no
Type_of_Assembly
PE
Clustering_Similarity%
0.85
Minimum within individual coverage level to include a read for assembly (K1)
6
Minimum number of individuals a read must be present in to include for assembly (K2)
6
Mapping_Reads?
yes
Mapping_Match_Value
1
Mapping_MisMatch_Value
4
Mapping_GapOpen_Penalty
6
Calling_SNPs?
yes_

I'd really appreciate it if anyone could give me some suggestions.

Thanks,
Tong

**Comment by jpuritz** [comment]
For debugging or troubleshooting, please include the following information:

The last output in dDocent.runs file
The entire dDocent_main.LOG
The output of ls -l in your working directory

**Comment by jpuritz** [comment]
You can also check the bwa log file for that sample
