### ISSUE TITLE
remove duplicates prior to variant calling

### ISSUE THREAD

**Issue by pdimens** [jpuritz/dDocent#78]
I've been reading up on Freebayes and some best-practices and found several recommendations ([1](https://bcbio.wordpress.com/2013/10/21/updated-comparison-of-variant-detection-methods-ensemble-freebayes-and-minimal-bam-preparation-pipelines/),[2](https://github.com/freebayes/freebayes#input-filters)) for using `samtools markdup` on alignment .bam files prior to variant calling.
By doing so, `freebayes` will skip over alignments marked as duplicates. 

Is there a reason dDocent doesn't perform this post-alignment processing step?

**Comment by jpuritz** [comment]
This type of duplicate detection will not work for any ddRAD libraries.  It relies solely on the mapping coordinates, with any PE reads having the same start and end coordinates being called as duplicates.  When all your reads start at two RE sites, this would mark nearly all reads as duplicates.

**Comment by pdimens** [comment]
Ah, gotcha. Thanks for the explanation
