### ISSUE TITLE
ulimit silent error (bug)

### ISSUE THREAD

**Issue by pdimens** [jpuritz/dDocent#79]
I recently had variant calling finish, and somewhere in the terminal log was a minor mention of mawk being unable to open `mapped.somenumber.bed` because of an open file limit. The issue is that despite this error, freebayes still ran and dDocent still finished, and had I not spotted that single mention of mawk failure, I wouldn't have noticed something was wrong. That instance of freebayes ran for ~24hrs and since changing the ulimit, it's been running >48hrs (and still going), so the error had a pretty substantial impact on how many instances of freebayes dDocent was creating. 

I _think_ I isolated the `mawk` part creating the `mapped.??.bed` files. Is there a way to introduce logic to this so it will error and exit if it fails, rather than continuing to run freebayes anyway?

https://github.com/jpuritz/dDocent/blob/270bc93fba35b70e041a48ccc9d749122b85fec3/dDocent#L497-L504

**Comment by jpuritz** [comment]
73a01502425cfdc812299d98ffcc5f01dd78f468 Should fix this.  Please test and let me know.
