### ISSUE TITLE
missing data in merged vcf file

### ISSUE THREAD

**Issue by alxcmrn** [jpuritz/dDocent#82]
I've noticed that missing data in my merged vcf file following genotyping are haploid ".:" while all genotypes with data are correctly diploid. Running the` sed -e 's/       \.\:/   \.\/\.\:/g'  `line on the merged vcf file does not resolve the issue.  However, using `'s/.:.:.:.:.:.:.:./.\/\.:.:.:.:.:.:.:./g'` does resolve ploidy of missing genotypes. Just curious as to why the line from the pipeline was not functioning. 

Missing data within the raw*.vcf files is coded as a single "." without additional fields 

Using vcflib ver 1.0.2 for vcfcombine.

Cheers,
-Alex

**Comment by jpuritz** [comment]
`sed -e 's/       \.\:/   \.\/\.\:/g'` needs to have literal tabs for it to work.  There may be an issue with tab character encoding.
