### ISSUE TITLE
#'head: cannot open 'reference.fasta' for reading: No such file or directory' while running denovo assembly

### ISSUE THREAD

**Issue by santoshkumarrana** [jpuritz/dDocent#87]
I was running denovo assembly on SE RAD-seq reads, and prepared all infile and config.ctl file according to dDocent manual. The program runs with an error somewhere in bwa saying: 
'head: cannot open 'reference.fasta' for reading: No such file or directory'
Creating alignment intervals
Cannot open "reference.fasta.fai"No such file or directory
mawk: cannot open reference.fasta.fai (No such file or directory)
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.

I tried all the way re-installing conda env, packages, file permission (but file permission gets changed after running ddocent from '-rwxrwxrwx' to '-rw-rw----'.
Please find the attached log file contents.

dDocent version 2.9.4 started Fri Feb 17 01:46:58 EST 2023 

At this point, all configuration information has been entered and dDocent may take several hours to run.
It is recommended that you move this script to a background operation and disable terminal input and output.
All data and logfiles will still be recorded.
To do this:
Press [01;33mcontrol[0m and [01;33mZ[0m simultaneously
Type [01;33mbg[0m and press enter
Type [01;33mdisown -h[0m and press enter
Now sit back, relax, and wait for your analysis to finish

Trimming reads
Removing the _1 character and replacing with /1 in the name of every sequence

Using BWA to map reads
head: cannot open 'reference.fasta' for reading: No such file or directory

Creating alignment intervals
Cannot open "reference.fasta.fai"No such file or directory
mawk: cannot open reference.fasta.fai (No such file or directory)
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
.
.
.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.
Error: The genome file genome.file has no valid entries (are you sure it's a 2-column bedtools genome file). Exiting.

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
head: cannot open 'reference.fasta' for reading: No such file or directory

gzip: stdout: Broken pipe
.
.
.
gzip: stdout: Broken pipe

gzip: stdout: Broken pipe

gzip: stdout: Broken pipe
Genomic interval creation completed successfully.

Using FreeBayes to call SNPs
popmap file not found, building a new one from the sample names
ls: cannot access 'mapped.*.bed': No such file or directory
rm: cannot remove 'mapped.*.bed': No such file or directory
could not open "raw.*.vcf" exiting
mv: cannot stat 'raw.*.vcf': No such file or directory

Using VCFtools to parse TotalRawSNPS.vcf for SNPs that are called in at least 90% of individuals

dDocent has finished with an analysis in /storage/home/sqr5923/scratch/rudhir/ddocent 

dDocent started Fri Feb 17 01:46:58 EST 2023 

dDocent finished Fri Feb 17 04:08:54 EST 2023 

After filtering, kept 0 out of a possible 0 Sites 

dDocent 2.9.4 
The 'd' is silent, hillbilly.

**Comment by pdimens** [comment]
Hey there, sorry for the delayed response. Can you verify that there is a `reference.fasta` file in your working directory?

**Comment by santoshkumarrana** [comment]
> 
Hi,
I am running denovo assembly. I guess we don't need to provide reference.fasta in working directly. But instead, dDocent should be able to map the input reads and build reference.fasta itself. But its not working.

**Comment by pdimens** [comment]
The main dDocent executable does not automatically build a de novo assembly. You will need to use the included RefMap etc scripts to accomplish that.
