### ISSUE TITLE
Info about the number of mapped reads etc.

### ISSUE THREAD

**Issue by Anto007** [jpuritz/dDocent#90]
Hi @jpuritz @pdimens

Great pipeline and thank you for bringing this out to the community! I would appreciate it very much if you could let me know where in the dDocent output I can find information such as the number of reads mapped to the reference transcriptome for each individual, mean coverage, etc?

**Comment by Anto007** [comment]
If I look into the individual sample cov.stats files as below, is it correct that the last column represents the mean coverage values? Is it possible to also find somewhere in the output the info for the number of reads mapped here? Many thanks in advance @jpuritz @pdimens  

```
head Sample1.cov.stats 
comp5	0	439	2
comp6	0	67	0
comp10	0	505	2
comp12	3	388	5
comp14	18	314	21
comp22	0	298	13
comp24	0	355	4
comp27	0	408	0
comp29	0	365	0
comp31	0	392	6
```

**Comment by jpuritz** [comment]
This is the output of `bedtools coverage -b Sample1-RG.bam -a mapped.bed -counts -sorted -g genome.file > Sample1.cov.stats`

It's `bed` format:
`contig` `start coordinate` `end coordinate` `count of reads that overlap with the interval`


Hopefully, `Sample1` is just an example name, but you should be following the dDocent naming convention `PopulationIdentifier_SampleIdentifier`.  Also, dDocent is not designed for transcriptomics.

**Comment by Anto007** [comment]
@jpuritz Many thanks for your prompt response-much appreciated! Yes, Sample1 is just an example name and I'm following the dDocent naming convention. My input data is from ezRADseq. I notice that there's also `cov.stats` and `cov.split.stats` available in my results directory. Do they represent just the mean number of read counts across all the samples that were analyzed?

**Comment by jpuritz** [comment]
No.  cov.stats is the sum.  Cov.split.stats is used for creating SNP
calling intervals.  It can be ignored.

Jon Puritz, PhD (he/him)

Associate Professor
Department of Biological Sciences
University of Rhode Island
120 Flagg Road, Kingston, RI 02881


Webpage: MarineEvoEco.com

Cell:    401-338-8739
Work:  401-874-9020

"The most valuable of all talents is that of never using two words when one
will do.” -Thomas Jefferson
--------------------------------------------
*The University of Rhode Island occupies the traditional stomping ground of
the Narragansett Nation and the Niantic People. *

**Comment by Anto007** [comment]
Thank you very much again
